[package]
name = "bayesld"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bayesld"
crate-type = ["cdylib", "rlib"]

[dependencies]
numpy = "0.27.1"
pyo3 = "0.27.0"

[dev-dependencies]
rand = "0.8"
criterion = "0.5"

[[bench]]
name = "bayesld_bench"
harness = false
